
variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
cache:
  paths:
    - node_modules/
stages:
  - build
  - deploy
build:
  stage: build
  script:
    - docker build -t $TAG_COMMIT .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $TAG_COMMIT

deploy_dev:
  stage: deploy
  script:
    - docker login -u deploy@dxmb.vn -p $DOCKER_KEY $CI_REGISTRY
    - sh docker-compose.dev.sh $CI_COMMIT_SHORT_SHA
    - docker stack deploy --compose-file docker-compose.dev.yml qsland_dev --with-registry-auth
  only:
    - dev
deploy_product:
  stage: deploy
  script:
    - cd /data/webroot/booking_online_qsland_web && git pull && npm install && npm run build && pm2 restart 3
  only:
    - master
  tags:
    - product